name: Release

on:
  # Support manually pushing a new release
  workflow_dispatch: {}
  # Trigger when a release is published
  release:
    types: [published]

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Publish to NPM
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4
        with:
          version: 10
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: Install Dependencies
        run: |
          pnpm install

      - name: Build project
        run: |
          pnpm run build

      - name: Push Release
        if: ${{ !github.event.release.prerelease }}
        run: |
          pnpm publish --tag latest --access=public --no-git-checks --provenance

      - name: Push Pre-Release
        if: ${{ github.event.release.prerelease }}
        run: |
          pnpm publish --tag next --access=public --no-git-checks --provenance
